### PR TITLE
Fix logic for determining whether on front domain or admin domain

### LINKED ISSUE #119: Unable to register callback on `wp_front_service_worker` action
I'm trying to register a service worker in a plugin I'm developing. I've installed `pwa-wp`, and then added this to my [plugin-name].php file, and it isn't doing anything.

```php
function registerServiceWorker()
{
	var_dump('hello');die;
}

\add_action(
	"wp_front_service_worker",
	"registerServiceWorker"
);
```

What do I need to do to be able to use this action so I can go on to register my service worker script?

Thanks!

### PR DESCRIPTION
**Pull request by narthur**
Resolves #119 by taking port into account when determining whether the request is on admin or front. Previous to this, if a port was included in `home_url()` or `admin_url()`, the respective `$on_front_domain` and `$on_admin_domain` variables would always evaluate to false.

This PR is based on #121.

### CODE REVIEW

File: wp-includes/service-workers.php [hunk 1]
```diff
@@ -113,8 +113,17 @@ function wp_print_service_workers() {
...
-	$on_front_domain = isset( $_SERVER['HTTP_HOST'] ) && wp_parse_url( home_url(), PHP_URL_HOST ) === $_SERVER['HTTP_HOST'];
-	$on_admin_domain = isset( $_SERVER['HTTP_HOST'] ) && wp_parse_url( admin_url(), PHP_URL_HOST ) === $_SERVER['HTTP_HOST'];
+	$home_port  = wp_parse_url( home_url(), PHP_URL_PORT );
+	$admin_port = wp_parse_url( admin_url(), PHP_URL_PORT );
+
+	$home_host  = wp_parse_url( home_url(), PHP_URL_HOST );
+	$admin_host = wp_parse_url( admin_url(), PHP_URL_HOST );
+
+	$home_url  = ( $home_port ) ? "$home_host:$home_port" : $home_host;
+	$admin_url = ( $admin_port ) ? "$admin_host:$admin_port" : $admin_port;
```
Comment (westonruter) [inline wp-includes/service-workers.php]: It looks like there is a bug here:

```suggestion
	$admin_url = ( $admin_port ) ? "$admin_host:$admin_port" : $admin_host;
```
